config/routes.rb
Geobob::Application.routes.draw do
  
  root :to => 'default#index'
  
  # top level pages
  match '/contact' => 'default#contact', :as => :contact
  match '/sitemap' => 'default#sitemap', :as => :sitemap
  match '/ping' => 'default#ping', :as => :ping
  match '/about' => 'default#about', :as => :about
  match '/demos' => 'default#demos', :as => :demos
  
  match 'admin' => 'admin/dashboard#index'
  
  devise_for :users
  
  namespace "admin" do
    resources :users
  end
  
  resources :facts do
    resources :contents do
      post :sort, :on => :collection
    end
  end
  
  resources :projects do
    resources :facts do
      post :sort, :on => :collection
    end
    collection do
      get :details
      post :details
    end
    member do
      get :export
      get :details
      post :details
      put :details
      get :content
      get :build
      get :icons
    end
  end
  resources :app_links
  resources :app_feeds
  resources :app_maps

end

app/models/app_link.rb
# == Schema Information
#
# Table name: app_links
#
#  id                :integer         not null, primary key
#  title             :string(255)
#  url               :string(2083)
#  icon_file_name    :string(255)
#  icon_content_type :string(255)
#  icon_file_size    :integer
#  created_at        :datetime
#  updated_at        :datetime
#

class AppLink < ActiveRecord::Base
  
  belongs_to :project
  
  attr_protected :created_at, :updated_at
  
  has_attached_file :icon, 
                    :styles => { :phone => "57x57>" },
                    :default_url => "/images/author_imgs/icon_links.png"
                    
end

app/controllers/app_links_controller.rb
class AppLinksController < ApplicationController
                
  before_filter :authenticate_user!
  before_filter :setup_app_link, :only => [:edit, :update, :destroy]
          
  def create
    @app_link = AppLink.new(params[:app_link])
    @item_id = params[:item_id]
    @success = @app_link.save
    respond_to do |format|
      format.js { render :template => false }
    end
  end
  
  def edit
    render :layout => false
  end
  
  def update
    @success = @app_link.update_attributes(params[:app_link])
    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  def destroy
    @app_link.destroy
    respond_to do |format|
      format.js { render :template => false }
    end
  end
  
  protected
    def setup_app_link
      @app_link = AppLink.find(params[:id])
    end
    
end

app/views/app_links/_app_link.erb
<div id="<%=app_item.dom_id%>" class="icon">
  <a class="delete ajax-delete" href="<%= app_link_path(app_item) %>"><img src="/images/fancybox/fancy_closebox.png" /></a>
  <a class="fancy_app_edit" href="<%= edit_app_link_path(app_item) %>"><%= image_tag(app_item.icon.url(:phone), :class => 'link') %></a>
  <caption><%= app_item.title %></caption>
</div>

app/views/app_links/_form.erb
<%= semantic_form_for @app_link, :html => { :multipart => true, :class => 'ajax' } do |f| -%>
  <div id="messages-container">
    <%= output_errors('Please correct the following errors:', {:class => 'help-box'}, @app_link) %>
  </div>
  <% f.inputs do %>
    <%= f.input :title -%>
    <%= f.input :url -%>
  <% end -%>
  <%= f.file_field :icon, { :label => 'Upload Icon' } %>
  <div class="submits clearfix form-item">
    <div class="waiting" style="display:none;">Please Wait</div>
    <%= f.submit 'Save', :class => 'submit_wait submit_fact' %>
  </div>
<% end -%>

app/views/app_links/create.js.erb
<% if @success -%>
	jQuery('#<%=@item_id%>').replaceWith('<%= escape_javascript(render('app_links/app_link', :app_item => @app_link)) %>');
	apply_content_fancybox();
<% else -%>
	<%= output_errors_ajax('messages-container', 'Please correct the following errors:', {:class => 'help-box'}, @app_link, true) %>
<% end -%>

app/views/app_links/destroy.js.erb
jQuery("#<%=@app_link.dom_id%>").remove();

app/views/app_links/edit.erb
<%= render 'app_links/form' %>
<script type="text/javascript" language="JavaScript">
  jQuery(document).ready(function() {
    apply_ajax_forms();
  });
</script>

app/views/app_links/update.js.erb
<% if @success -%>
	jQuery('#<%=@app_link.dom_id%>').replaceWith(decodeHtml('<%= escape_javascript(render('app_links/app_link', :app_item => @app_link)) %>'));
	jQuery.fancybox.close();
	apply_content_fancybox();
<% else -%>
	<%= output_errors_ajax('messages-container', 'Please correct the following errors:', {:class => 'help-box'}, @app_link, true) %>
<% end -%>