config/routes.rb
Geobob::Application.routes.draw do
  
  root :to => 'default#index'
  
  # top level pages
  match '/contact' => 'default#contact', :as => :contact
  match '/sitemap' => 'default#sitemap', :as => :sitemap
  match '/ping' => 'default#ping', :as => :ping
  match '/about' => 'default#about', :as => :about
  match '/demos' => 'default#demos', :as => :demos
  
  match 'admin' => 'admin/dashboard#index'
  
  devise_for :users
  
  namespace "admin" do
    resources :users
  end
  
  resources :facts do
    resources :contents do
      post :sort, :on => :collection
    end
  end
  
  resources :projects do
    resources :facts do
      post :sort, :on => :collection
    end
    collection do
      get :details
      post :details
    end
    member do
      get :export
      get :details
      post :details
      put :details
      get :content
      get :build
      get :icons
    end
  end
  resources :app_links
  resources :app_feeds
  resources :app_maps

end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :fact
  has_many :answers, :dependent => :destroy
  has_many :ispies, :dependent => :destroy

  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a['answer'].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :ispies, :reject_if => proc { |attrs| attrs['position_x'].blank? || attrs['position_y'].blank? }

  attr_accessible :content, :answers_attributes, :position, :category, :ispies_attributes, :video

  scope :by_position, :order => "position ASC"
  scope :only_questions, where(:category => 'question')
  scope :only_ispies, where(:category => 'ISpy')
  scope :only_contents, where(:category => 'content')
  #commented by Atul
  #scope :only_contents, where(:category => 'narration')

  before_create :set_position, :set_category

  has_attached_file :video
                    #,:default_url => "http://www.google.com/mapfiles/marker.png"
  
  def set_position
    last_content = self.fact.contents.by_position.last
    if last_content
      self.position = last_content.position + 1
    else
      self.position = 1
    end
  end
  
  def set_category
    self.category = 'category' if !self.category
  end
  
  def json_hash
    h = {
      :content => self.content,
      :position => self.position,
    }
    if self.is_question?
      h[:answers] = self.answers.collect{|a| a.json_hash}
      h[:video] = video #added by Atul
    elsif self.is_ISpy?
      h[:objects] = self.ispies.collect{|is| is.json_hash}
      h[:image] = video
    end
    h
  end
  
  def is_question?
    self.category == 'question'
  end
  

  def is_content?
    self.category == 'content'
  end

  #Commented by Atul  
  # Below lines are added by Atul 
  #def is_content?
   # self.category == 'narration'
  #end
  

  def is_ISpy?
    self.category == 'ISpy'
  end

  def self.categories
    ['content', 'question', 'ISpy']
  end

  #commented by Atul
  #below lines are added by Atul as now the category content has changed to narration
  #def self.categories
   # ['narration', 'question', 'ISpy']
  #end
  
  def video
    "#{self.video_file_name}"
  end

  def self.fix_position
    facts = Fact.all
    facts.each do |fact|
      contents = fact.contents.by_position
      contents.each_with_index do |content, index|
        content.update_attribute(:position, index + 1)
      end
    end
  end  
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                 :integer         not null, primary key
#  project_type_id    :integer
#  name               :string(255)
#  description        :text
#  deadline           :datetime
#  aasm_state         :string(255)
#  photo_file_name    :string(255)
#  photo_content_type :string(255)
#  photo_file_size    :integer
#  comment_count      :integer         default(0)
#  created_at         :datetime
#  updated_at         :datetime
#  app_items          :text
#

require 'zip/zip'
require 'zip/zipfilesystem'
class Project < ActiveRecord::Base
  
  include AASM
  include ZipMethods
  
  belongs_to :project_type
  belongs_to :project_layout
  has_many :project_roles
  has_many :users, :through => :project_roles
  has_many :facts, :as => :factable
  has_many :app_maps
  has_many :app_links
  has_many :app_feeds
  
  acts_as_mappable
  acts_as_taggable
  has_friendly_id :name, :use_slug => true
  
  validates_presence_of :name
  validates_presence_of :description
  
  attr_protected :created_at, :updated_at
  
  has_attached_file :photo, 
                    :styles => { :medium => "300x300>",
                                 :thumb => "100x100>",
                                 :icon => "50x50>",
                                 :tiny => "24x24>" },
                    :default_url => "/images/project_default.jpg"
                
  has_attached_file :app_icon, 
                    :styles => { :medium => "300x300>",
                                 :thumb => "100x100>",
                                 :icon => "50x50>",
                                 :tiny => "24x24>" },
                    :default_url => "/images/project_default.jpg"
                    
  has_attached_file :splash_image, 
                    :styles => { :phone => "320x480",
                                 :background => "276x400" },
                    :default_url => "/images/project_default.jpg"
                    
  has_attached_file :background_image, 
                    :styles => { :phone => "320x480",
                                 :background => "276x400",
                                 :standard_background => "400x400#" },
                    :default_url => "/images/background_default.jpg"
                    
  aasm_initial_state :new
  
  aasm_state :new
  aasm_state :suggested
  aasm_state :finished

  aasm_event :finish do
    transitions :to => :finished, :from => [:new]
  end
    
  scope :by_name, :order => "name ASC"
  scope :recent, lambda { { :conditions => ['created_at > ?', 1.week.ago] } }
  scope :newest, :order => "created_at DESC"
  
  before_save :sanitize_attributes

  # Set this value to a specific user to customize the santize level for that user
  attr_accessor :current_editor
  
  def can_edit?(user)
    return false if user.blank?
    return true if user.admin?
    self.users.include?(user)
  end
  
  # Sanitize content before saving.  This prevent XSS attacks and other malicious html.
  def sanitize_attributes
    if self.sanitize_level
      self.description = Sanitize.clean(self.description, self.sanitize_level)
      self.name = Sanitize.clean(self.name, self.sanitize_level)
    end
  end
  
  # Override this method to control sanitization levels.
  # Currently a user who is an admin will not have their content sanitized.  A user
  # in any role 'editor', 'manager', or 'contributor' will be given the 'RELAXED' settings
  # while all other users will get 'BASIC'.
  #
  # Options are from sanitze:
  # nil - no sanitize
  # Sanitize::Config::RELAXED
  # Sanitize::Config::BASIC
  # Sanitize::Config::RESTRICTED
  # for more details see: http://rgrove.github.com/sanitize/
  def sanitize_level
    return Sanitize::Config::BASIC if self.current_editor.nil?
    return nil if self.current_editor.admin?
    return Sanitize::Config::RELAXED if self.current_editor.any_role?('editor', 'manager', 'contributor')
    Sanitize::Config::BASIC
  end

  # Generate a zip file containing all relevant files from the project
  # Code helps from:
  # http://rubyzip.sourceforge.net/
  # http://info.michael-simons.eu/2008/01/21/using-rubyzip-to-create-zip-files-on-the-fly/
  # http://74.125.155.132/search?q=cache:m4XaoZ1tRasJ:www.superwick.com/archives/2007/06/14/generating-zip-file-archives-via-ruby-on-rails/+ruby+on+rails+Tempfile+zip&cd=1&hl=en&ct=clnk&gl=us
  # http://railstalk.com/2009/8/6/create-a-zip-file-using-ruby
  def zip(path)
    FileUtils.mkdir_p(path)
    zip_file_path = File.join(path, "#{self.to_param}.zip")
    if File.exists?(zip_file_path)
      File.delete(zip_file_path)
    end
    
    # open or create the zip file
    Zip::ZipFile.open(zip_file_path, Zip::ZipFile::CREATE) do |zip_file|
      
      # Add data files
      project_for_zip(zip_file, 'project.js')
      tags_for_zip(zip_file, 'category.js')

      app_maps.each do |map|
        map.facts_for_zip(zip_file, "map_#{map.id}_project.js")
        map.tags_for_zip(zip_file, "map_#{map.id}_category.js")
      end
      
      # Add images
      images_dir = 'images'
      zip_file.mkdir(images_dir) unless zip_file.find_entry(images_dir)
      self.facts.collect do |fact|
#        begin
          zip_file.add(fact.image, fact.photo.path(:thumb)) unless fact.photo_file_name.nil? || zip_file.find_entry(fact.image)
        # rescue => ex
        #   # Need a way to output these errors
        # end
      end
      
    end
    File.chmod(0644, zip_file_path)
    zip_file_path
  end

end

app/models/project_type.rb
# == Schema Information
#
# Table name: project_types
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class ProjectType < ActiveRecord::Base
  
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
                
  before_filter :authenticate_user!
  
  def sort
    @fact = Fact.find(params[:fact_id])
    # Sortable lists with jQuery:
    # http://awesomeful.net/posts/47-sortable-lists-with-jquery-in-rails
    @contents = @fact.contents.by_position
    @contents.each do |content|
      content.position = params['content'].index(content.id.to_s) + 1
      content.save
    end
    respond_to do |format|
      format.js { render :layout => false }
    end
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
                
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :get_project, :only => [:show, :edit, :destroy, :interface, :details, :content, :build]
  # added by Atul
  before_filter :verify_user, :only => [:edit, :destroy]
  
  layout :choose_layout
                
  def index
    @user = User.find(params[:user]) if params[:user]
    #below line added by Atul
    @online_users = User.online_users
    @project = Project.new
    if @user
      @projects = @user.projects
    else
      @projects = Project.by_name.paginate(:page => @page, :per_page => @per_page)
    end
    respond_to do |format|
      format.html
      format.xml  { render :xml => @projects }
      format.json { render :json => @projects.to_json }
    end
  end

  def show
    @facts = @project.facts.by_position
    @tags = @project.tags.all(:order => 'name')
    @fact = Fact.new
    @page_title = @project.name
    respond_to do |format|
      format.html { redirect_to edit_project_path(@project) }
      format.xml  { render :xml => @project }
      format.json { render :json => { :project => @project, :facts => @facts.collect{|fact| fact.json_hash}}.to_json }
    end
  end
  
  def new
    @project = Project.new
    respond_to do |format|
      format.html
      format.xml  { render :xml => @project }
    end
  end

  def edit
  end
  
  def interface
    render
  end
  
  def icons
    @project = Project.find(params[:id])
    @project_icons = @project.tags
    @available_icons = ActsAsTaggableOn::Tag.all - @project_icons
  end
  
  def details
    # This is a bit of a hack since updates should be handled by update but we need to make sure and capture the layout change if the user changes it
    @project.update_attributes!(params[:project]) if !@project.blank?
    @project ||= Project.new(params[:project])
  end
  
  def content
    @icons = []
    @icons.concat(@project.app_maps)
    @icons.concat(@project.app_links)
    @icons.concat(@project.app_feeds)
    @icons.sort {|a,b| b.sort <=> a.sort}
    if @project.project_layout.view == 'gpsrs'
      if @project.facts.empty?
        # create a default starting point
        @fact = @project.facts.create(:title => 'start', :content => 'This is your starting point', :vertical_offset => 0, :horizontal_offset => 0)
      else
        @fact = Fact.new
      end
      @fact.add_default_questions
      @fact.add_default_contents
    end
  end
  
  def build
    render
  end
  
  def export
    @project = Project.find(params[:id])
    send_file @project.zip("#{::Rails.root.to_s}/public/projects/"), :type => 'application/zip'
  end
  
  def create  
    @project = current_user.projects.create(params[:project])
    @project.current_editor = current_user
    #ProjectRole.create(:user_id => current_user.id, :project_id => @project.id)
    respond_to do |format|
      if @project
        #flash[:notice] = 'Project was successfully created.'
        format.html { redirect_to content_project_path(@project) }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "details" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @project = Project.find(params[:id])
    if params[:read_google_map]
      @project.read_google_map
    else
      @project.current_editor = current_user
      success = @project.update_attributes(params[:project])
    end
    
    respond_to do |format|
      if success
        format.html do
          #flash[:notice] = 'Project was successfully updated.'
          redirect_to content_project_path(@project)
        end
        format.js { render :layout => false }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.js do
          @errors = @project.errors.full_messages.to_sentence
          render :template => false
        end
        format.xml { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
  
  protected
    
    def get_project
     @project = Project.find(params[:id]) rescue nil     
    end
    
    def verify_user
      unless(current_user.admin? || current_user.owner?(params[:id]))
        redirect_to(projects_url, :notice => 'Access denied. You can edit projects created by you only')
      end
    end
    
    def choose_layout
      'default'
    end
    
    # def facts_to_categories(facts)
    #   categories = {}
    #   facts.each do |fact|
    #     if fact.tags.length > 0
    #       fact.tags.each do |tag|
    #         categories[tag.name.to_sym] = [] unless categories.has_key?(tag.name.to_sym)
    #         categories[tag.name.to_sym] << fact
    #       end
    #     else
    #       categories[:uncategorized] = [] unless categories.has_key?(:uncategorized)
    #       categories[:uncategorized] << fact
    #     end
    #   end
    #   categories
    # end
    
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def box_size
    400
  end
  
  def empty_project
    return true if @project.blank?
    return true if @project.id.blank?
    false
  end
  
  def app_background(project, include_style = true, no_background = false, include_border = false)
    style = "height:#{box_size}px;"
    style << "width:#{box_size}px;"
    if !no_background && project.background_image
      style << %Q{background-image:url('#{project.background_image.url(:standard_background)}');}
    end
    if include_border
      style << "border:solid 2px #000;"
    end
    if include_style
      %Q{style="#{style}"}
    else
      style
    end
  end
  
  def app_splash(project, include_style = true)
    if project.splash_image
      back = %Q{background-image:url('#{project.splash_image.url(:background)}');}
      if include_style
        %Q{style="#{back}"}
      else
        back
      end
    end
  end
  
  def output_icons(app_items)
    app_items.each do |app_item|
      concat(render("#{app_item.class.to_s.tableize.pluralize}/#{app_item.class.to_s.tableize.singularize}", :app_item => app_item))
    end
  end
  
  def calculate_gpsrs_position(fact)
    height = fact.factable.height || 100
    width = fact.factable.width || 100
    vscale = box_size/height
    hscale = box_size/width
    
    height = height/2
    width = width/2
    
    v = fact.vertical_offset || 0
    h = fact.horizontal_offset || 0

    v = height - v
    h = h + width
    
    v = v * vscale
    h = h * hscale
    
    %Q{style="top:#{v}px;left:#{h}px;position:absolute;"}
  end

  def show_video(content)
    if content.is_question?
      'display:inline;'
    else
      'display:none;'
    end
  end
  
  def content_is_question_css(content)
    if content.is_question?
      'display:block;'
    else
      'display:none;'
    end
  end
  
  def content_has_ispy_css(content)
    if content.is_ISpy?
      'display:block;'
    else
      'display:none;'
    end
  end  
end

app/views/projects/content/_flow.html.erb
Not yet implemented

app/views/projects/content/_gpsrs.html.erb
<div id="author_leftcolumn">
  <h6>Step 1: Upload Background</h6>
  <p>Click ‘browse’ to upload a personal picture then drag your background to the phone.</p>

  <%= semantic_form_for @project, :html => { :multipart => true, :class => 'ajax gpsrs-project-basic-settings' } do |f| -%>
    <div id="messages-container">
      <%= output_errors('Please correct the following errors:', {:class => 'help-box'}, @project) %>
    </div>
    <% f.inputs do %>    
      <%= f.file_field :background_image, { :label => '<strong>App Background: </strong>(Image size should match the size you specify above.)' } %>
      <p>Enter the size of the play area in meters.</p>
      <%= f.input :width %>
      <%= f.input :height %>
    <% end -%>
    <div class="submits clearfix form-item">
      <div class="waiting" style="display:none;">Please Wait</div>
      <%= f.submit 'Save', :input_html => { :class => 'submit_wait' } %>
      <%= hidden_field_tag :update_app_icons_drop, true %>
    </div>
  <% end -%>
  
  <div class="cl"></div>
  <br />
  <h6> Step 2: Add Points</h6>
  <p>Add points to the map to identify the course your students will take.</p>
  <div id="gps-points">
    <div id="new-fact">
      <%#= render :partial => 'facts/gpsrs_fact_form' %>
      <a href="<%=new_project_fact_path(@project)%>" class="gpsrs-view fancy-gpsrs">Add new point</a>
    </div>  
  </div>
  <br />
  <p><a href="<%= build_project_path %>"><img width="182" height="40" alt="Next" src="/images/author_imgs/next_button3.png"></a></p>
</div>
<div id="author_rightcolumn">
  <div class="content-iPhone">
    <div id="gpsrs-points-container" class="points-container" <%= app_background(@project).html_safe %>>
      <%= render :partial => 'facts/gpsrs_fact', :collection => @project.facts, :as => :fact %>
    </div>
  </div>
  <div id="gpsrs-points-control" class="center"><a href="<%=project_facts_path(@project)%>" class="fancy-edit">Reorder points</a></div>
</div>

<script type="text/javascript">
jQuery(document).ready(function() {
  apply_fancy_gpsrs();
  make_gpsrs_dots_dnd();
  jQuery('.fact-content').live('keyup', function(){
    jQuery('#gpsrs-preview').html(jQuery(this).val());
  });
  jQuery('.fact-content').live('click', function(){
    jQuery('#gpsrs-preview').html(jQuery(this).val());
  });
  jQuery('.gpsrs-iphone-trigger').live('click', function(){
    var textarea = jQuery(this).parent().find('textarea');
    textarea.val(jQuery('.gpsrs-iphone-template').html());
    textarea.keyup();
    return false;
  });
    	
});
</script>

app/views/projects/content/_grid.html.erb
<div id="author_leftcolumn">
  <h6>Step 1: Upload Background</h6>
  <p>Click ‘browse’ to upload a personal picture then drag your background to the phone.</p>

  <%= semantic_form_for @project, :html => { :multipart => true, :class => 'ajax' } do |f| -%>
    <div id="messages-container">
      <%= output_errors('Please correct the following errors:', {:class => 'help-box'}, @project) %>
    </div>
    <%= f.file_field :background_image, { :label => '<strong>App Background: </strong>(RECOMMENDED: 320 X 480 px JPG at 160 dpi)' } %>
    <div class="submits clearfix form-item">
      <div class="waiting" style="display:none;">Please Wait</div>
      <%= f.submit 'Upload', :class => 'submit_wait' %>
      <%= hidden_field_tag :update_app_icons_drop, true %>
    </div>
  <% end -%>
  
  <div class="cl"></div>
  <br />
  <h6> Step 2: Choose and Configure your icons</h6>
  <p>Grab which icon best describes the functionality you would like to use and drag them onto the phone. After dropping the icon, you will be prompted to edit the icon’s content and details.</p>
  <h2>**DRAG ICONS ONTO PHONE**</h2>
  <div id="app-icons" class="connectedSortable">
    <div class="icon">
      <img src="/images/author_imgs/icon_RSS.png" alt="icon_RSS" width="57" height="57" class="rss" />
      <caption>RSS</caption>
    </div>
    <div class="icon">
      <img src="/images/author_imgs/icon_links.png" alt="icon_links" width="58" height="57" class="link" />
      <caption>Link</caption>
    </div>
    <div class="icon">
      <img src="/images/author_imgs/icon_maps.png" alt="icon_maps" width="67" height="57" class="map" />
      <caption>Map</caption>
    </div>
    <div class="icon" style="display:none;">
      <img src="/images/author_imgs/icon_photos.png" alt="icon_photo" width="71" height="51" class="photo" />
      <caption>Photo Gallery</caption>
    </div>
  </div>
  <br />
  <p><a href="<%= build_project_path %>"><img width="182" height="40" alt="Next" src="/images/author_imgs/next_button3.png"></a></p>
</div>
<div id="author_rightcolumn">
  <div class="content-iPhone">
    <div id="app-icons-drop" class="connectedSortable points-container" <%= app_background(@project).html_safe %>>
      <% output_icons(@icons) %>
    </div>
  </div>
</div>

<script type="text/javascript">

var icon_id = 0;
var $drop;

jQuery(document).ready(function() {
  
  $drop = jQuery('#app-icons-drop');

	jQuery("#app-icons-drop .icon").live('mouseover mouseout',
		function(event) {
		  if (event.type == 'mouseover') {
        jQuery(this).find('.delete').show();
      } else {
        jQuery(this).find('.delete').hide();
      }
    }
	);

	jQuery("#app-icons .icon").draggable({
		appendTo: "body",
		helper: "clone",
		zIndex: 1000000
	});
	
	$drop.droppable({
	  accept: "#app-icons .icon",
	  drop: function(event, ui) {
			add_icon(ui.draggable);
		}
  }).sortable({
    connectWith: '.connectedSortable',
		sort: function() {
		},
		update: function(event, ui) {
      var order = jQuery(this).sortable('toArray').toString();
      // TODO Submit new icon ordering to the server. This will probably go to the app_map object. Which means the app_map will need a way to hold it.
    }
	}).disableSelection();
  
  apply_content_fancybox();
  
});

function get_order() {
  //return jQuery('#app-icons-drop').sortable('toArray').toString();
  return jQuery('#app-icons-drop').sortable('serialize');
}

function add_icon($item) {
  var $new_item = $item.clone().appendTo($drop).show();
  var type = $item.children('img').attr('class');
  var new_data = { 'type': type };
  var url = '';
  icon_id += 1;
  $new_item.attr("id", "icon_" + icon_id);
  var data = { '_method': 'post', 'format': 'js', 'item_id': $new_item.attr("id") };
  switch (type) {
    case 'link':  
      url = '/app_links/';
      data['app_link[project_id]'] = <%= @project.id %>;
      data['app_link[title]'] = 'Link';
      data['app_link[url]'] = 'http://www.example.com';
      break;
    case 'rss':
      url = '/app_feeds/';
      data['app_feed[project_id]'] = <%= @project.id %>;
      data['app_feed[title]'] = 'RSS';
      data['app_feed[url]'] = 'http://www.example.com/rss';
      break;
    case 'map':
      url = '/app_maps/';
      data['app_map[project_id]'] = <%= @project.id %>;
      break;
  }
  jQuery.post(url, data);
}

function apply_content_fancybox(){
  jQuery('.fancy_app_edit').fancybox({ 'overlayShow' : false, 'hideOnOverlayClick' : false, 'hideOnContentClick' : false }); 
}

</script>

<% content_for :head do -%>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <%= javascript_include_tag 'map.js' %>
<% end -%>

app/views/projects/content/_list.html.erb
Not yet implemented
<%#= render 'facts/map', :facts => @app_map.facts, :factable => @app_map, :tags => @app_map.tags %>