config/routes.rb
Geobob::Application.routes.draw do
  
  root :to => 'default#index'
  
  # top level pages
  match '/contact' => 'default#contact', :as => :contact
  match '/sitemap' => 'default#sitemap', :as => :sitemap
  match '/ping' => 'default#ping', :as => :ping
  match '/about' => 'default#about', :as => :about
  match '/demos' => 'default#demos', :as => :demos
  
  match 'admin' => 'admin/dashboard#index'
  
  devise_for :users
  
  namespace "admin" do
    resources :users
  end
  
  resources :facts do
    resources :contents do
      post :sort, :on => :collection
    end
  end
  
  resources :projects do
    resources :facts do
      post :sort, :on => :collection
    end
    collection do
      get :details
      post :details
    end
    member do
      get :export
      get :details
      post :details
      put :details
      get :content
      get :build
      get :icons
    end
  end
  resources :app_links
  resources :app_feeds
  resources :app_maps

end

app/models/fact.rb
class Fact < ActiveRecord::Base
  
  include AASM
  include LocationMethods
  
  validates_presence_of :title
  #validates_presence_of :location
  #validates_presence_of :content
  validates_presence_of :factable
  
  belongs_to :factable, :polymorphic => true
  acts_as_mappable
  acts_as_taggable
  
  has_many :contents, :dependent => :destroy, :order => 'position ASC'
  
  accepts_nested_attributes_for :contents, :reject_if => lambda { |a| a['content'].blank? }, :allow_destroy => true
  
  has_attached_file :photo, 
                    :styles => { :medium => "300x300>",
                                 :thumb => "100x100>",
                                 :icon => "50x50>",
                                 :tiny => "24x24>" },
                                 :default_url => "http://www.google.com/mapfiles/marker.png"
  
  attr_accessible :title, :subtitle, :horizontal_offset, :content, :vertical_offset, :latitude, :longitude, 
                  :pincolor, :animate, :rightButton, :mapButton, :homepage, :image, :category, :tag_list, :contents_attributes
  
  aasm_initial_state :new

  aasm_state :new
  aasm_state :approved

  aasm_event :approve do
    transitions :to => :approved, :from => [:new]
  end
  
  scope :by_position, :order => "position ASC, id ASC"
  
  before_create :set_position
  
  def add_default_questions
    1.times do
      question = self.contents.build(:category => 'question')
      4.times { question.answers.build }
    end
  end  
  
  def add_default_contents
    1.times do
      narration = self.contents.build(:category => 'content')
    end
  end
  
  def categories
    categories = self.tags.collect{ |tag| tag.name }
    categories = ['uncategorized'] if categories.blank?
    categories
  end
  
  def icon
    if self.photo.original_filename
      self.photo.url(:icon)
    elsif tag = self.tags.first
      tag.icon
    else
      '/images/dot.png'
      #'http://maps.google.com/mapfiles/marker.png'
    end
  end
  
  # Methods for json export
  def latitude
    self.lat
  end
  
  def longitude
    self.lng
  end
  
  def pincolor
    'red'
  end
  
  def animate
    true
  end
  
  def rightButton
    "arrow.png"
  end
  
  def mapButton
    "map.png"
  end
  
  def homepage
    "main.html?id=#{self.id}"
  end
  
  def image
    "images/#{self.photo_file_name}"
    self.photo.url(:thumb)    
  end
  
  def category
    tag = self.tags.first
    if tag
      tag.name
    else
      ''
    end
  end
  
  def set_position
    last_fact = self.factable.facts.by_position.last
    if last_fact
      self.position = last_fact.position + 1
    else
      self.position = 1
    end
  end
  
  def json_hash
    
    { :id => id,
      :position => position,
      :title => title || "#{id}",
      :subtitle => subtitle,
      :content => content,
      :latitude => latitude,
      :longitude => longitude,
      :pincolor => pincolor,
      :animate => animate,
      :rightButton => rightButton,
      :mapButton => mapButton,
      :homepage => homepage,
      :icon => icon,
      :image => image,
      :category => category,
      :vertical_offset => vertical_offset,
      :horizontal_offset => horizontal_offset,
      :questions => self.contents.only_questions.by_position.includes(:answers).collect{|c| c.json_hash},
      :ISpy => self.contents.only_ispies.by_position.includes(:ispies).collect{|is| is.json_hash},
      :contents => self.contents.only_contents.by_position.collect{|c| c.json_hash} 
    }
  end
  
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
                
  before_filter :authenticate_user!
  before_filter :setup_parent, :only => [:index, :sort, :new]
  
  uses_tiny_mce(:options => GlobalConfig.map_mce_options,
                :only => [:edit])
  
  def index
    @facts = @parent.facts.by_position
    respond_to do |format|
      format.js { render :layout => false }
    end
  end
  
  def sort
    # Sortable lists with jQuery:
    # http://awesomeful.net/posts/47-sortable-lists-with-jquery-in-rails
    @facts = @parent.facts.by_position
    @facts.each do |fact|
      fact.position = params['fact'].index(fact.id.to_s) + 1
      fact.save
    end
    @facts = @parent.facts.by_position # Reload the facts
    respond_to do |format|
      format.js { render :layout => false }
    end
  end
  
  def new
    @factable = @parent
    @fact = @parent.facts.new
    setup_project_layout    
    if @project.project_layout.view == 'gpsrs'
      @fact.add_default_questions
      @fact.add_default_contents
    end
    respond_to do |format|
      format.html
      format.js do
        @enable_js = true
        render :layout => false
      end
    end
  end
                  
  def create
    @factable = params[:factable_type].to_s.constantize.find(params[:factable_id])
    @fact = @factable.facts.build(params[:fact])
    @gprs = true if params[:spatial]
    @fact.set_lat_lng_from_location unless @gprs # WARNING set_lat_lng_from_location  gelocates addresses.  Even if you give it a lat,lng it will find the nearest valid address
    if @success = @fact.save
      @message = "Successfully created."
      @categories = @fact.categories
    else
      if @fact.content
        @message = "There was a problem adding the fact"
      else
        @message = "There was a problem adding your information"
      end
    end
    respond_to do |format|
      format.html { redirect_to(@fact.project) }
      format.js { render :layout => false }
    end
  end
  
  def edit
    @fact = Fact.find(params[:id])
    @factable = @fact.factable
    setup_project_layout
    respond_to do |format|
      format.html
      format.js do
        @enable_js = true
        render :layout => false
      end
    end
  end
  
  def update
    @fact = Fact.find(params[:id])
    if params[:horizontal_offset] && params[:vertical_offset]
      @full_update = false
      @gpsrs = true
      success = @fact.update_attributes(:horizontal_offset => params[:horizontal_offset], :vertical_offset => params[:vertical_offset])
    elsif params[:lat] && params[:lng]
      @full_update = false
      success = @fact.update_attributes(:lat => params[:lat], :lng => params[:lng])
    else
      @full_update = true
      @fact.attributes = params[:fact]
      @gpsrs = true if params[:spatial]
      @fact.set_lat_lng_from_location unless @gpsrs # WARNING set_lat_lng_from_location  gelocates addresses.  Even if you give it a lat,lng it will find the nearest valid address
      success = @fact.save
    end

    # Output message if needed.
    if !success
      @message = "There was a problem updating #{@fact.title}: #{@fact.errors.full_messages.to_sentence}"
    end
    
    @icon = @fact.icon
    respond_to do |format|
      format.html { redirect_to(@fact.project) }
      format.js { render :layout => false }
    end
  end

  def destroy
    @fact = Fact.find(params[:id])
    @gpsrs = true if params[:spatial]
    @factable = @fact.factable
    @fact.destroy
    respond_to do |format|
      format.html { redirect_to(@factable) }
      format.js { render :layout => false }
    end
  end
  
  protected

    def setup_project_layout
      if @factable && @factable.respond_to?(:project_layout)
        @project = @factable
        if(@project.project_layout.view == 'gpsrs')
          @custom_view = @project.project_layout.view
        end
      end
    end
    
end

app/views/facts/_answer_fields.erb
<div class="answer fields">
  <p class="title">Answer <%= remove_child_link "(remove)", f %></p>
  <ul>
    <%= f.input :answer %>
    <%= f.input :correct_feedback %>
    <%= f.input :incorrect_feedback %>
    <%= f.input :correct %>
  </ul>
</div>

app/views/facts/_content_fields.erb
<li id="<%= f.object.dom_id if f.object %>" class="fields content-container">
  <ul>
    <li>
      <%= f.label :content, "Content" %>
      <%= remove_child_link "Remove", f %>
      <a class="gpsrs-iphone-trigger" href="#">Add Template</a>
    </li>
    <li>
      <%= f.label :category, "Content Category" %>
      <%= f.select :category, Content.categories, {:include_blank => false}, :class => 'content-category-select' %>
    </li>                         	
    <li><%= f.text_area :content, :rows => 3, :class => 'fact-content' %></li>

    
    <%= f.input :video, :label => 'Upload Data', :as => 'file'%>
    
    <li style="<%=content_is_question_css(f.object)%>" class="content-answers-container">
      <a href="#" class="content-answers-toggle">Show Answers</a>
      <div style="display:none;" class="content-answers">
        <%= f.semantic_fields_for :answers do |a| %>
          <%= render 'facts/answer_fields', :f => a %>
        <% end %>
        <div><%= add_child_link "Add Answer", f, :answers %></div>
      </div>
    </li>

    <li style="<%=content_has_ispy_css(f.object)%>" class="content-ispy-container">
      <%= f.semantic_fields_for :ispies do |is| %>
        <%= render 'facts/ispy_fields', :f => is %>
      <% end %>
      <div><%= add_child_link "Add ISpy Details", f, :ispies %></div>
   </li>
  </ul>
</li>

app/views/facts/_form.html.erb
<% 
if @fact.blank?
  prefix = 'fact'
else
  prefix = @fact.dom_id
end
form_id = "#{prefix}_content_form"
mce_id = "#{prefix}_mce_content"
-%>
<%= semantic_form_for :fact, :html => { :multipart => true, :id => form_id, :class => 'ajax' } do |f| -%>
  <div id="messages-container">
    <%= output_errors('Please correct the following errors:', {:class => 'help-box'}, @fact) %>
  </div>
  <% f.inputs do %>
    <%= f.input :title, :label => 'Title' -%>
    <%= f.input :content, :class => 'mceEditor', :id => mce_id %>
    <% if !new_fact -%>
      <%= f.input :location, :label => 'Location', :input_html => { :class => 'location' } -%>
    <% else -%>
      <%= f.input :location, :input_html => { :hidden => true } -%>
    <% end -%>
  <% end -%>
  <% factable.tags.each do |tag| -%>
    <a class="tag-link" href="#" title="<%= tag.name %>" <%=show_icon_tag?(new_fact)%>><img <%=current_tag_class(@fact, tag)%> src="<%= tag.icon %>" alt="<%= tag.name %>" /></a>
  <% end -%>
  <%= f.hidden_field :tag_list, { :class => 'tag_list' }  -%>
  <%= hidden_field_tag :factable_id, factable.id if factable %>
  <%= hidden_field_tag :factable_type, factable.type if factable %>
  <%= f.file_field :photo, { :label => 'Upload Image' } %>
  <div class="submits clearfix form-item">
    <div class="waiting" style="display:none;">Please Wait</div>
    <%= f.submit 'Save', :class => 'submit_wait submit_fact' %>
  </div>
<% end -%>

app/views/facts/_gpsrs_fact.erb
<div id="<%=fact.dom_id%>" class="gpsrs-fact-dot-container" <%=calculate_gpsrs_position(fact).html_safe%>>
  <div id="<%=fact.dom_id%>_dot" class="gpsrs-fact-dot">
    <img src="<%= fact.icon -%>" alt="Icon for fact" /><a href="<%=edit_fact_path(fact)%>" class="gpsrs-view fancy-gpsrs"><%=fact.position%>. <%= fact.title[0..4] %></a>
  </div>
  <input type="hidden" value="<%=fact.id%>" class="fact_id">
</div>

app/views/facts/_gpsrs_fact_form.erb
<div id="gpsrs-editor-popup">
  <div id="gpsrs-editor-leftcolumn">
    <%= semantic_form_for @fact, :html => { :multipart => true, :class => 'ajax gpsrs-form' } do |f| -%>
      <div id="messages-container">
        <%= output_errors('Please correct the following errors:', {:class => 'help-box'}, @fact) %>
      </div>
      <div id="ajax-messages-container"></div>
      <%= f.inputs do %>
        <%= f.input :title, :label => 'Title' -%>
        <li>
          <p><label>Select Icon</label></p>
          <% @project.tags.each do |tag| -%>
            <a class="tag-link" href="#" title="<%= tag.name %>" <%=show_icon_tag?(@fact.new_record?)%>><img <%=current_tag_class(@fact, tag)%> src="<%= tag.icon %>" alt="<%= tag.name %>" /></a>
          <% end -%>
          <%= f.hidden_field :tag_list, { :class => 'tag_list' }  -%>
        </li>
        <%= f.input :photo, :label => 'Upload Image', :as => 'file' %>
        <%= f.input :vertical_offset, :input_html => { :class => 'number' }, :label => 'North/South offset' %>
        <%= f.input :horizontal_offset, :input_html => { :class => 'number' }, :label => 'East/West offset' %>
      <% end -%>

      <div id="child-content">
        <ul id="content-list">
          <%= f.semantic_fields_for :contents do |q| -%>
            <%= render :partial => "facts/content_fields", :locals => { :f => q } %>
          <% end -%>
          <div id="add-child-content"><%= add_child_link "Add Content", f, :contents %></div>
        </ul>
      </div>
  
      <%= hidden_field_tag :factable_id, @project.id %>
      <%= hidden_field_tag :factable_type, @project.type %>
      <%= hidden_field_tag :spatial, true %>
      <div class="submits clearfix form-item">
        <div class="waiting" style="display:none;">Please Wait</div>
        <%= f.submit 'Save', :class => 'submit_wait submit_fact' %>
        <% if !@fact.new_record? -%>
          <a class="delete ajax-delete" href="<%= fact_path(@fact, :spatial => true) %>">Delete this point</a>
        <% end -%>
      </div>
    <% end -%>
  </div>
  <div id="gpsrs-editor-rightcolumn">
    <div class="content-iPhone">
      <div id="gpsrs-preview" class="points-container" <%= app_background(@project, true, true, true).html_safe %>></div>
    </div>
  </div>
</div>
<div class="gpsrs-iphone-template" style="display:none;">
  <style type="text/css">
  /* <![CDATA[ */
  .style01{color:#FFFFFF;font-family:Arial,Helvetica,sans-serif;font-size:16px;}
  body{margin:0;padding:0;font-size:16;font-family:sans-serif;}
  #container{/* Replace "ContentBackground001.jpg" with your own background image. */
  background-image:url(ContentBackground001.jpg);width:320px;height:350px;padding:0;border:0;overflow:hidden;}
  #header{width:320px;height:18px;padding:0;border:0;overflow:hidden;}
  #footer{width:320px;height:30px;padding:0;}
  #text{width:244px;height:130px;padding:0;overflow:hidden;margin:10px 38px 10px 38px}
  #content01{width:320px;height:144px;padding:0;overflow:hidden;}
  #content02{width:320px;height:138px;padding:0;overflow:hidden;}
  #divider{width:320px;height:26px;padding:0;}
  /* ]]> */
  </style>
  <div id="container">
    <div id="header"></div>
    <div id="content01">
      <!--Replace "ContentImage.jpg" here with your own image. -->
      <div align="center"><img width="242" height="144" src="ContentImage.jpg"></div>
    </div>
    <div id="divider"></div>
    <div id="content02">
      <div id="text" class="style01">
        <!--Replace "Place Text Here" with your own text. -->
        <p>Place Text Here</p>
        <p>Place Text Here</p>
      </div>
    </div>
    <div id="footer"></div>
  </div>
</div>

<script type="text/javascript" language="JavaScript">
  jQuery(document).ready(function() {
    <% if @fact.new_record? -%>
      apply_content_methods('', false);
    <% else -%>
      apply_content_methods('<%= sort_fact_contents_path(@fact) %>', true);
    <% end -%>
  });
</script>

app/views/facts/_ispy_fields.erb
  <p><u>Target Image Details</u></p>
  <ul>
    <%= f.input :position_x %>
    <%= f.input :position_y %>
    <%= f.input :trigger_x %>
    <%= f.input :trigger_y %>
    <%= f.input :checker_x %>
    <%= f.input :checker_y %>
    <%= f.input :checker_size %>
  </ul>

app/views/facts/_list_fact.erb
<li id="<%= fact.dom_id %>"><%= fact.title %></li>

app/views/facts/_question_fields.erb
<hr />
<div class="question fields">
  <div>
    <%= f.label :content, "Question" %>
    <%= remove_child_link "remove", f %><br />
    <%= f.input :content, :rows => 3 %>
  </div>
  <%= f.semantic_fields_for :answers do |a| %>
    <%= render 'facts/answer_fields', :f => a %>
  <% end %>
  <div><%= add_child_link "Add Answer", f, :answers %></div>
</div>

app/views/facts/create.js.erb
jQuery('.waiting').hide();
jQuery('.submit_wait').show();
<% if @success -%>
	<% if @gprs -%>
		var fact_content = '<%=escape_javascript(render(:partial => 'facts/gpsrs_fact', :locals => { :fact => @fact })).html_safe%>';
		jQuery('#gpsrs-points-container').append(decodeHtml(fact_content));
		apply_fancy_gpsrs();
	<% else -%>
		var fact_content = '<%=escape_javascript(render(:partial => 'facts/fact', :locals => { :fact => @fact }))%>';
		infowindow.setContent(decodeHtml(fact_content));
		jQuery('#facts').append(fact_content);
		markers['<%=@fact.dom_id%>'] = setupMarker('<%=@fact.id%>', '<%=@fact.dom_id%>', '<%=@fact.title%>', new google.maps.LatLng(<%=@fact.latlng%>), '<%=@fact.icon%>');
		infowindow.open(map, markers['<%=@fact.dom_id%>']);
		applyEditor();
		paletteControl.shutDownKillMarker();
	<% end -%>
	jQuery.fancybox.close();
<% else -%>
	<%= output_errors_ajax('ajax-messages-container', 'Please correct the following errors:', {:class => 'help-box'}, @fact, true) %>
<% end -%>

app/views/facts/edit.erb
<% if @custom_view %>
	<%= render :partial => "facts/#{@custom_view}_fact_form" %>
<% else -%>
	<%= render :partial => 'facts/form', :locals => { :factable => @factable, :new_fact => false } %>
<% end -%>

<% if @enable_js -%>
<script type="text/javascript" language="JavaScript">
  jQuery(document).ready(function() {
    apply_ajax_forms();
		applyEditor();
  });
</script>
<% end -%>

app/views/facts/edit.js.erb
<% if @custom_view %>
	<%= render :partial => "facts/#{@custom_view}_fact_form" %>
<% else -%>
	<%= render :partial => 'facts/form', :locals => { :project => nil, :new_fact => false } %>
<% end -%>

<script type="text/javascript" language="JavaScript">
  jQuery(document).ready(function() {
    apply_ajax_forms();
		applyEditor();
  });
</script>

app/views/facts/index.erb
<div id="sort-facts-container">
  <h1>Reorder map points</h1>
	<ol id="sort-facts">
	  <%= render :partial => 'facts/list_fact', :collection => @facts, :as => :fact %>
	</ol>
</div>

<script type="text/javascript" language="JavaScript">
  jQuery(document).ready(function() {
    apply_fact_sort('<%= sort_project_facts_path(@project) %>');
  });
</script>

app/views/facts/new.erb
<% if @custom_view %>
	<%= render :partial => "facts/#{@custom_view}_fact_form" %>
<% else -%>
	<%= render :partial => 'facts/form', :locals => { :factable => @parent, :new_fact => true } %>
<% end -%>

<% if @enable_js -%>
<script type="text/javascript" language="JavaScript">
  jQuery(document).ready(function() {
    apply_ajax_forms();
		applyEditor();
  });
</script>
<% end -%>

app/views/facts/sort.js.erb
jQuery("#gpsrs-points-container").html(decodeHtml("<%= escape_javascript(render(:partial => 'facts/gpsrs_fact', :collection => @facts, :as => :fact)) %>"));