config/routes.rb
Geobob::Application.routes.draw do
  
  root :to => 'default#index'
  
  # top level pages
  match '/contact' => 'default#contact', :as => :contact
  match '/sitemap' => 'default#sitemap', :as => :sitemap
  match '/ping' => 'default#ping', :as => :ping
  match '/about' => 'default#about', :as => :about
  match '/demos' => 'default#demos', :as => :demos
  
  match 'admin' => 'admin/dashboard#index'
  
  devise_for :users
  
  namespace "admin" do
    resources :users
  end
  
  resources :facts do
    resources :contents do
      post :sort, :on => :collection
    end
  end
  
  resources :projects do
    resources :facts do
      post :sort, :on => :collection
    end
    collection do
      get :details
      post :details
    end
    member do
      get :export
      get :details
      post :details
      put :details
      get :content
      get :build
      get :icons
    end
  end
  resources :app_links
  resources :app_feeds
  resources :app_maps

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                 :integer         not null, primary key
#  project_type_id    :integer
#  name               :string(255)
#  description        :text
#  deadline           :datetime
#  aasm_state         :string(255)
#  photo_file_name    :string(255)
#  photo_content_type :string(255)
#  photo_file_size    :integer
#  comment_count      :integer         default(0)
#  created_at         :datetime
#  updated_at         :datetime
#  app_items          :text
#

require 'zip/zip'
require 'zip/zipfilesystem'
class Project < ActiveRecord::Base
  
  include AASM
  include ZipMethods
  
  belongs_to :project_type
  belongs_to :project_layout
  has_many :project_roles
  has_many :users, :through => :project_roles
  has_many :facts, :as => :factable
  has_many :app_maps
  has_many :app_links
  has_many :app_feeds
  
  acts_as_mappable
  acts_as_taggable
  has_friendly_id :name, :use_slug => true
  
  validates_presence_of :name
  validates_presence_of :description
  
  attr_protected :created_at, :updated_at
  
  has_attached_file :photo, 
                    :styles => { :medium => "300x300>",
                                 :thumb => "100x100>",
                                 :icon => "50x50>",
                                 :tiny => "24x24>" },
                    :default_url => "/images/project_default.jpg"
                
  has_attached_file :app_icon, 
                    :styles => { :medium => "300x300>",
                                 :thumb => "100x100>",
                                 :icon => "50x50>",
                                 :tiny => "24x24>" },
                    :default_url => "/images/project_default.jpg"
                    
  has_attached_file :splash_image, 
                    :styles => { :phone => "320x480",
                                 :background => "276x400" },
                    :default_url => "/images/project_default.jpg"
                    
  has_attached_file :background_image, 
                    :styles => { :phone => "320x480",
                                 :background => "276x400",
                                 :standard_background => "400x400#" },
                    :default_url => "/images/background_default.jpg"
                    
  aasm_initial_state :new
  
  aasm_state :new
  aasm_state :suggested
  aasm_state :finished

  aasm_event :finish do
    transitions :to => :finished, :from => [:new]
  end
    
  scope :by_name, :order => "name ASC"
  scope :recent, lambda { { :conditions => ['created_at > ?', 1.week.ago] } }
  scope :newest, :order => "created_at DESC"
  
  before_save :sanitize_attributes

  # Set this value to a specific user to customize the santize level for that user
  attr_accessor :current_editor
  
  def can_edit?(user)
    return false if user.blank?
    return true if user.admin?
    self.users.include?(user)
  end
  
  # Sanitize content before saving.  This prevent XSS attacks and other malicious html.
  def sanitize_attributes
    if self.sanitize_level
      self.description = Sanitize.clean(self.description, self.sanitize_level)
      self.name = Sanitize.clean(self.name, self.sanitize_level)
    end
  end
  
  # Override this method to control sanitization levels.
  # Currently a user who is an admin will not have their content sanitized.  A user
  # in any role 'editor', 'manager', or 'contributor' will be given the 'RELAXED' settings
  # while all other users will get 'BASIC'.
  #
  # Options are from sanitze:
  # nil - no sanitize
  # Sanitize::Config::RELAXED
  # Sanitize::Config::BASIC
  # Sanitize::Config::RESTRICTED
  # for more details see: http://rgrove.github.com/sanitize/
  def sanitize_level
    return Sanitize::Config::BASIC if self.current_editor.nil?
    return nil if self.current_editor.admin?
    return Sanitize::Config::RELAXED if self.current_editor.any_role?('editor', 'manager', 'contributor')
    Sanitize::Config::BASIC
  end

  # Generate a zip file containing all relevant files from the project
  # Code helps from:
  # http://rubyzip.sourceforge.net/
  # http://info.michael-simons.eu/2008/01/21/using-rubyzip-to-create-zip-files-on-the-fly/
  # http://74.125.155.132/search?q=cache:m4XaoZ1tRasJ:www.superwick.com/archives/2007/06/14/generating-zip-file-archives-via-ruby-on-rails/+ruby+on+rails+Tempfile+zip&cd=1&hl=en&ct=clnk&gl=us
  # http://railstalk.com/2009/8/6/create-a-zip-file-using-ruby
  def zip(path)
    FileUtils.mkdir_p(path)
    zip_file_path = File.join(path, "#{self.to_param}.zip")
    if File.exists?(zip_file_path)
      File.delete(zip_file_path)
    end
    
    # open or create the zip file
    Zip::ZipFile.open(zip_file_path, Zip::ZipFile::CREATE) do |zip_file|
      
      # Add data files
      project_for_zip(zip_file, 'project.js')
      tags_for_zip(zip_file, 'category.js')

      app_maps.each do |map|
        map.facts_for_zip(zip_file, "map_#{map.id}_project.js")
        map.tags_for_zip(zip_file, "map_#{map.id}_category.js")
      end
      
      # Add images
      images_dir = 'images'
      zip_file.mkdir(images_dir) unless zip_file.find_entry(images_dir)
      self.facts.collect do |fact|
#        begin
          zip_file.add(fact.image, fact.photo.path(:thumb)) unless fact.photo_file_name.nil? || zip_file.find_entry(fact.image)
        # rescue => ex
        #   # Need a way to output these errors
        # end
      end
      
    end
    File.chmod(0644, zip_file_path)
    zip_file_path
  end

end

app/models/project_type.rb
# == Schema Information
#
# Table name: project_types
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class ProjectType < ActiveRecord::Base
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
                
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :get_project, :only => [:show, :edit, :destroy, :interface, :details, :content, :build]
  # added by Atul
  before_filter :verify_user, :only => [:edit, :destroy]
  
  layout :choose_layout
                
  def index
    @user = User.find(params[:user]) if params[:user]
    #below line added by Atul
    @online_users = User.online_users
    @project = Project.new
    if @user
      @projects = @user.projects
    else
      @projects = Project.by_name.paginate(:page => @page, :per_page => @per_page)
    end
    respond_to do |format|
      format.html
      format.xml  { render :xml => @projects }
      format.json { render :json => @projects.to_json }
    end
  end

  def show
    @facts = @project.facts.by_position
    @tags = @project.tags.all(:order => 'name')
    @fact = Fact.new
    @page_title = @project.name
    respond_to do |format|
      format.html { redirect_to edit_project_path(@project) }
      format.xml  { render :xml => @project }
      format.json { render :json => { :project => @project, :facts => @facts.collect{|fact| fact.json_hash}}.to_json }
    end
  end
  
  def new
    @project = Project.new
    respond_to do |format|
      format.html
      format.xml  { render :xml => @project }
    end
  end

  def edit
  end
  
  def interface
    render
  end
  
  def icons
    @project = Project.find(params[:id])
    @project_icons = @project.tags
    @available_icons = ActsAsTaggableOn::Tag.all - @project_icons
  end
  
  def details
    # This is a bit of a hack since updates should be handled by update but we need to make sure and capture the layout change if the user changes it
    @project.update_attributes!(params[:project]) if !@project.blank?
    @project ||= Project.new(params[:project])
  end
  
  def content
    @icons = []
    @icons.concat(@project.app_maps)
    @icons.concat(@project.app_links)
    @icons.concat(@project.app_feeds)
    @icons.sort {|a,b| b.sort <=> a.sort}
    if @project.project_layout.view == 'gpsrs'
      if @project.facts.empty?
        # create a default starting point
        @fact = @project.facts.create(:title => 'start', :content => 'This is your starting point', :vertical_offset => 0, :horizontal_offset => 0)
      else
        @fact = Fact.new
      end
      @fact.add_default_questions
      @fact.add_default_contents
    end
  end
  
  def build
    render
  end
  
  def export
    @project = Project.find(params[:id])
    send_file @project.zip("#{::Rails.root.to_s}/public/projects/"), :type => 'application/zip'
  end
  
  def create  
    @project = current_user.projects.create(params[:project])
    @project.current_editor = current_user
    #ProjectRole.create(:user_id => current_user.id, :project_id => @project.id)
    respond_to do |format|
      if @project
        #flash[:notice] = 'Project was successfully created.'
        format.html { redirect_to content_project_path(@project) }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "details" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @project = Project.find(params[:id])
    if params[:read_google_map]
      @project.read_google_map
    else
      @project.current_editor = current_user
      success = @project.update_attributes(params[:project])
    end
    
    respond_to do |format|
      if success
        format.html do
          #flash[:notice] = 'Project was successfully updated.'
          redirect_to content_project_path(@project)
        end
        format.js { render :layout => false }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.js do
          @errors = @project.errors.full_messages.to_sentence
          render :template => false
        end
        format.xml { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
  
  protected
    
    def get_project
     @project = Project.find(params[:id]) rescue nil     
    end
    
    def verify_user
      unless(current_user.admin? || current_user.owner?(params[:id]))
        redirect_to(projects_url, :notice => 'Access denied. You can edit projects created by you only')
      end
    end
    
    def choose_layout
      'default'
    end
    
    # def facts_to_categories(facts)
    #   categories = {}
    #   facts.each do |fact|
    #     if fact.tags.length > 0
    #       fact.tags.each do |tag|
    #         categories[tag.name.to_sym] = [] unless categories.has_key?(tag.name.to_sym)
    #         categories[tag.name.to_sym] << fact
    #       end
    #     else
    #       categories[:uncategorized] = [] unless categories.has_key?(:uncategorized)
    #       categories[:uncategorized] << fact
    #     end
    #   end
    #   categories
    # end
    
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def box_size
    400
  end
  
  def empty_project
    return true if @project.blank?
    return true if @project.id.blank?
    false
  end
  
  def app_background(project, include_style = true, no_background = false, include_border = false)
    style = "height:#{box_size}px;"
    style << "width:#{box_size}px;"
    if !no_background && project.background_image
      style << %Q{background-image:url('#{project.background_image.url(:standard_background)}');}
    end
    if include_border
      style << "border:solid 2px #000;"
    end
    if include_style
      %Q{style="#{style}"}
    else
      style
    end
  end
  
  def app_splash(project, include_style = true)
    if project.splash_image
      back = %Q{background-image:url('#{project.splash_image.url(:background)}');}
      if include_style
        %Q{style="#{back}"}
      else
        back
      end
    end
  end
  
  def output_icons(app_items)
    app_items.each do |app_item|
      concat(render("#{app_item.class.to_s.tableize.pluralize}/#{app_item.class.to_s.tableize.singularize}", :app_item => app_item))
    end
  end
  
  def calculate_gpsrs_position(fact)
    height = fact.factable.height || 100
    width = fact.factable.width || 100
    vscale = box_size/height
    hscale = box_size/width
    
    height = height/2
    width = width/2
    
    v = fact.vertical_offset || 0
    h = fact.horizontal_offset || 0

    v = height - v
    h = h + width
    
    v = v * vscale
    h = h * hscale
    
    %Q{style="top:#{v}px;left:#{h}px;position:absolute;"}
  end

  def show_video(content)
    if content.is_question?
      'display:inline;'
    else
      'display:none;'
    end
  end
  
  def content_is_question_css(content)
    if content.is_question?
      'display:block;'
    else
      'display:none;'
    end
  end
  
  def content_has_ispy_css(content)
    if content.is_ISpy?
      'display:block;'
    else
      'display:none;'
    end
  end  
end

app/views/projects/_comment.html.erb
<div id="<%= comment.dom_id %>">
  <span class="user"><%= link_to comment_owner.user, comment_owner.user %></span>
  <p><%= h comment.body %></p>
</div>

app/views/projects/_google_map_scripts.html.erb
<script type="text/javascript">
var map;
var markers = new Array();

google.setOnLoadCallback(function() {
  if (google.maps.BrowserIsCompatible()) {
    map = new google.maps.Map2(document.getElementById("<%=content_id%>"));
    map.setCenter(new google.maps.LatLng(<%=center_on.lat%>, <%=center_on.lng%>), 11);
    map.addControl(new google.maps.LargeMapControl());
    map.addControl(new google.maps.MapTypeControl());
    
    // Add listener to set location if the user clicks on the map
    GEvent.addListener(map, "click", function(overlay,latlng) {
      if (latlng) {
        jQuery('#fact_location').val(latlng);
      }
    });
    <% facts.each do |fact| -%>
      markers['<%=fact.dom_id%>'] = setupMarker(new GLatLng(<%=fact.latlng%>), '<%=fact.dom_id%>', '<%= "#{fact.photo(:tiny)}" %>');
      map.addOverlay(markers['<%=fact.dom_id%>']);
    <% end -%>
  }
});
jQuery(window).unload( function () { GUnload(); } );
</script>

app/views/projects/_project.html.erb
<div class="project">
  <%= link_to image_tag(project.photo.url(:thumb), :class => 'thumb'), project_path(project) %>
  <h2><%= link_to project.name, edit_project_path(project.id) %></h2>
  <p><%= link_to 'Edit',  edit_project_path(project) %></p>
  <p><%#= link_to 'Map',  map_project_path(project) %></p>
  <p><%= link_to 'Icons', icons_project_path(project) %></p>
  <p><%= link_to 'Export', export_project_path(project) %></p>
  <p><%= project.description.html_safe %></p>
  <p><%= link_to 'Delete', @project, :confirm => 'Are you sure?', :method => :delete if @project.can_edit?(current_user) %></p>
</div>

app/views/projects/_project_nav.erb
<div class="breadcrumb">
  <img src="/images/author_imgs/arrow_<%=number%>.jpg" alt="Breadcrumb Nav" width="496" height="20" border="0" usemap="#Map2" />
  <map name="Map2" id="Map2">
    <area shape="rect" coords="378,3,495,18" href="<%= empty_project ? '#' : build_project_path(@project) %>" target="_self" alt="Build App" />
    <area shape="rect" coords="266,3,365,16" href="<%= empty_project ? '#' : content_project_path(@project) %>" target="_self" alt="App Content" />
    <area shape="rect" coords="142,4,244,17" href="<%= empty_project ? '#' : details_project_path(@project) %>" target="_self" alt="New App" />
    <area shape="rect" coords="6,3,127,17" href="<%= empty_project ? new_project_path : edit_project_path(@project) %>" target="_self" alt="Choose Interface" />
  </map>
</div>

app/views/projects/build.html.erb
<%= render 'projects/project_nav', :number => 4 %>
<div id="author_leftcolumn">
  <h6> Step 1: What You're Missing</h6>
  <p>Below is a list of things that need to be completed in order for your app 
    to work correctly. You can still build it, but we don’t recommend it.
  </p>
  <form id="form2" name="form2" method="post" action="">
    <textarea name="Title" cols="40" rows="10" id="Title"></textarea>
  </form>
  <!--END OF STEP 1-->
  <br />
  <h6> Step 2: Review App Design</h6>
  <p>Click on the links above the phone to review your designs and icons</p>
  <h6> Step 3: Build your App</h6>
  <p>Click the “Build App” button to download the zip file.</p>
  <br /><p><a href="<%= export_project_path(@project) %>"><img src="/images/author_imgs/next_button4.png" alt="Next" width="127" height="40" /></a></p>
  <p><a href="/projects/<%= "#{@project.to_param}.zip" %>">Download Zip File (Be sure to press build first!)</a></p>
</div>
<div id="author_rightcolumn">
  <div align="center">
    <h6><img src="/images/author_imgs/iphone.jpg" alt="Phone" width="338" height="625" /></h6>
  </div>
</div>

app/views/projects/details.html.erb
<%= render 'projects/project_nav', :number => 2 %>
<%= render 'projects/form', :submit_name => 'Save Project' %>

app/views/projects/edit.html.erb
<%= render 'projects/project_nav', :number => 1 %>
<%= semantic_form_for @project, :url => details_project_path(@project) do |f| -%>
  <%= render 'projects/layout', :f => f %>
<% end -%>

app/views/projects/icons.html.erb
<div id="project-icons" class="text_field"> 
  <h1>Select Icons for <%= h @project.name %></h1>
  <p>
    <%= link_to 'Go to Project', @project %> | 
    <%= link_to 'All Projects', projects_path %>
  </p>
  <%= output_message_container('messages', 'messages-container') %>
  <div id="project-icons">
    <h2>Icons for Project</h2>
    <div id="select-icons-drop" class="connectedSortable">
      <%= render :partial => 'tags/tag', :collection => @project_icons %>
    </div>
  </div>
  <div id="available-icons">
    <h2>Available Icons</h2>
    <div id="select-icons-delete" class="connectedSortable">
      <%= render :partial => 'tags/tag', :collection => @available_icons %>
    </div>
  </div>
</div>
<div style="display:none;">
  <% form_for @project, :html => { :id => 'select-tag-form', :class => 'ajax' } do |f| -%>
    <%= f.hidden_field :tag_list, :class => 'select-tag-list' -%>
  <% end -%>
</div>

<script type="text/javascript" language="JavaScript">
  jQuery(document).ready(function() {
    apply_ajax_forms();
    apply_icon_dnd();
  });
</script>

app/views/projects/index.html.erb
<div id = "online_users">
  <h3>Online Users</h3>
  <%= render :partial => 'projects/online_users', :object => @online_users -%>
</div>

<div id="project-list" class="text_field"> 
  <h1>CURRENT PROJECTS:</h1>
  <p><%= link_to 'Add New Project', new_project_path %></p>
  <div>
    <%= render :partial => 'projects/project', :collection => @projects -%>
  </div>
</div>

app/views/projects/map.html.erb
<div id="map_content" style="height:100%; width:100%;"></div>
<div style="display:none;">
  <div id="project">
    <p>Facts (<span id="facts_count"><%=@facts.length%></span>)</p>
  </div>
  <div id="new-fact">
    <%= render :partial => 'facts/form', :locals => { :factable => @factable, :new_fact => true } %>
  </div>
  <div id="new-fact-full">
    <%= render :partial => 'facts/form', :locals => { :factable => @factable, :new_fact => false } %>
  </div>
  <div id="facts">
    <%= render :partial => 'facts/fact', :collection => @facts %>
  </div>
  <a id="open_new_fact" href="#new-fact-full">New Fact</a>
  <span id="waiting" class="waiting">Loading, please wait...</span>
</div>

<script type="text/javascript">
var projectLatLng = new google.maps.LatLng(<%=@project.latlng%>);
function setupMarkers(){
  <% if @facts.blank? -%>
    return false;
  <% else -%>
    <% @facts.each do |fact| -%>
      markers['<%=fact.dom_id%>'] = setupMarker('<%=fact.id%>', '<%=fact.dom_id%>', '<%=escape_javascript(fact.title)%>', new google.maps.LatLng(<%=fact.latlng%>), '<%=fact.icon%>');
    <% end -%>
    return true;
  <% end -%>
}
function setupTags(paletteControl){
  <% @tags.each do |tag| -%>
  paletteControl.addTool('<%= tag.icon %>');
  <% end -%>
}
</script>


<%= semantic_form_for @factable do |f| -%>
  <%= hidden_field_tag :read_google_map, true %>
  <%= f.submit 'Reload Pins From Google Map Feed', :class => 'wait-button' %>
  <div class="waiting">Parsing Google feed.  Please wait.</div>
<% end -%>

app/views/projects/new.html.erb
<%= render 'projects/project_nav', :number => 1 %>
<%= semantic_form_for @project, :url => details_projects_path do |f| -%>
  <%= render 'projects/layout', :f => f %>
  <%= hidden_field_tag :new_project, true %>
<% end -%>

app/views/projects/past.html.erb
<h1>Past Projects</h1>
<%= render :partial => 'projects/project', :collection => @projects -%>

app/views/projects/show.html.erb
<div class="text_field"> 
  <h1>Configure <%= h @project.name %></h1>
  <p><%= link_to 'All Projects', projects_path %></p>
  <%= output_message_container('messages', 'messages-container') %>
  <div id="project-icons">
    <h2>Current Project Configuration</h2>
    <div id="select-icons-drop">
      
      
    </div>
  </div>
  <div id="available-icons">
    <h2>Available Options</h2>
    <div id="select-icons-delete">
      
    </div>
  </div>
</div>
<div style="display:none;">
  <% form_for @project, :html => { :id => 'select-tag-form', :class => 'ajax' } do |f| -%>
    <%= f.hidden_field :tag_list -%>
  <% end -%>
</div>

app/views/projects/update.js.erb
<% if params[:update_app_icons_drop] -%>
	jQuery('.points-container').attr('style', "<%= escape_javascript(app_background(@project, false).html_safe) %>");	
<% elsif !@errors.blank? -%>
	jQuery('#message').html('<%= @errors %>');
<% end -%>
jQuery('.waiting').hide();
jQuery('.submit_wait').show();